version: 2.1

executors:
  node-executor:
    docker:
      - image: node:16.15.0

jobs:
  build:
    docker:
      - image: node:16.15.0

    steps:
      - checkout

      # Restore dependencies from cache
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-

      - run:
          name: Install dependencies
          command: yarn install
      - save_cache:
          key: v1-dependencies-{{ checksum "package.json" }}
          paths:
            - ./node_modules
workflows:
  version: 2
  build:
    jobs:
      - build:
          NODE_VERSION: '16.15.0'
