version: 2.1
jobs:
  build:
    docker:
      - image: node:16.15.0

    working_directory: ~/repo

    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-

      - run: yarn install
      # - run: yarn test //TODO: uncommit after first test
      # - run: yarn coverage //TODO: uncommit after first test

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
